# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/narval/programing/proyects/cmon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/narval/programing/proyects/cmon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/narval/programing/proyects/cmon/CMakeFiles /home/narval/programing/proyects/cmon//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/narval/programing/proyects/cmon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmon

# Build rule for target.
cmon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cmon
.PHONY : cmon

# fast build rule for target.
cmon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/build
.PHONY : cmon/fast

src/lib/cmon_config.o: src/lib/cmon_config.c.o
.PHONY : src/lib/cmon_config.o

# target to build an object file
src/lib/cmon_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_config.c.o
.PHONY : src/lib/cmon_config.c.o

src/lib/cmon_config.i: src/lib/cmon_config.c.i
.PHONY : src/lib/cmon_config.i

# target to preprocess a source file
src/lib/cmon_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_config.c.i
.PHONY : src/lib/cmon_config.c.i

src/lib/cmon_config.s: src/lib/cmon_config.c.s
.PHONY : src/lib/cmon_config.s

# target to generate assembly for a file
src/lib/cmon_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_config.c.s
.PHONY : src/lib/cmon_config.c.s

src/lib/cmon_errors.o: src/lib/cmon_errors.c.o
.PHONY : src/lib/cmon_errors.o

# target to build an object file
src/lib/cmon_errors.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_errors.c.o
.PHONY : src/lib/cmon_errors.c.o

src/lib/cmon_errors.i: src/lib/cmon_errors.c.i
.PHONY : src/lib/cmon_errors.i

# target to preprocess a source file
src/lib/cmon_errors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_errors.c.i
.PHONY : src/lib/cmon_errors.c.i

src/lib/cmon_errors.s: src/lib/cmon_errors.c.s
.PHONY : src/lib/cmon_errors.s

# target to generate assembly for a file
src/lib/cmon_errors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_errors.c.s
.PHONY : src/lib/cmon_errors.c.s

src/lib/cmon_inotify.o: src/lib/cmon_inotify.c.o
.PHONY : src/lib/cmon_inotify.o

# target to build an object file
src/lib/cmon_inotify.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_inotify.c.o
.PHONY : src/lib/cmon_inotify.c.o

src/lib/cmon_inotify.i: src/lib/cmon_inotify.c.i
.PHONY : src/lib/cmon_inotify.i

# target to preprocess a source file
src/lib/cmon_inotify.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_inotify.c.i
.PHONY : src/lib/cmon_inotify.c.i

src/lib/cmon_inotify.s: src/lib/cmon_inotify.c.s
.PHONY : src/lib/cmon_inotify.s

# target to generate assembly for a file
src/lib/cmon_inotify.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_inotify.c.s
.PHONY : src/lib/cmon_inotify.c.s

src/lib/cmon_print.o: src/lib/cmon_print.c.o
.PHONY : src/lib/cmon_print.o

# target to build an object file
src/lib/cmon_print.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_print.c.o
.PHONY : src/lib/cmon_print.c.o

src/lib/cmon_print.i: src/lib/cmon_print.c.i
.PHONY : src/lib/cmon_print.i

# target to preprocess a source file
src/lib/cmon_print.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_print.c.i
.PHONY : src/lib/cmon_print.c.i

src/lib/cmon_print.s: src/lib/cmon_print.c.s
.PHONY : src/lib/cmon_print.s

# target to generate assembly for a file
src/lib/cmon_print.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/cmon_print.c.s
.PHONY : src/lib/cmon_print.c.s

src/lib/parser/cmon_parser.o: src/lib/parser/cmon_parser.c.o
.PHONY : src/lib/parser/cmon_parser.o

# target to build an object file
src/lib/parser/cmon_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/parser/cmon_parser.c.o
.PHONY : src/lib/parser/cmon_parser.c.o

src/lib/parser/cmon_parser.i: src/lib/parser/cmon_parser.c.i
.PHONY : src/lib/parser/cmon_parser.i

# target to preprocess a source file
src/lib/parser/cmon_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/parser/cmon_parser.c.i
.PHONY : src/lib/parser/cmon_parser.c.i

src/lib/parser/cmon_parser.s: src/lib/parser/cmon_parser.c.s
.PHONY : src/lib/parser/cmon_parser.s

# target to generate assembly for a file
src/lib/parser/cmon_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/parser/cmon_parser.c.s
.PHONY : src/lib/parser/cmon_parser.c.s

src/lib/utils/cmon_int_array.o: src/lib/utils/cmon_int_array.c.o
.PHONY : src/lib/utils/cmon_int_array.o

# target to build an object file
src/lib/utils/cmon_int_array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_int_array.c.o
.PHONY : src/lib/utils/cmon_int_array.c.o

src/lib/utils/cmon_int_array.i: src/lib/utils/cmon_int_array.c.i
.PHONY : src/lib/utils/cmon_int_array.i

# target to preprocess a source file
src/lib/utils/cmon_int_array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_int_array.c.i
.PHONY : src/lib/utils/cmon_int_array.c.i

src/lib/utils/cmon_int_array.s: src/lib/utils/cmon_int_array.c.s
.PHONY : src/lib/utils/cmon_int_array.s

# target to generate assembly for a file
src/lib/utils/cmon_int_array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_int_array.c.s
.PHONY : src/lib/utils/cmon_int_array.c.s

src/lib/utils/cmon_ps_tree.o: src/lib/utils/cmon_ps_tree.c.o
.PHONY : src/lib/utils/cmon_ps_tree.o

# target to build an object file
src/lib/utils/cmon_ps_tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_ps_tree.c.o
.PHONY : src/lib/utils/cmon_ps_tree.c.o

src/lib/utils/cmon_ps_tree.i: src/lib/utils/cmon_ps_tree.c.i
.PHONY : src/lib/utils/cmon_ps_tree.i

# target to preprocess a source file
src/lib/utils/cmon_ps_tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_ps_tree.c.i
.PHONY : src/lib/utils/cmon_ps_tree.c.i

src/lib/utils/cmon_ps_tree.s: src/lib/utils/cmon_ps_tree.c.s
.PHONY : src/lib/utils/cmon_ps_tree.s

# target to generate assembly for a file
src/lib/utils/cmon_ps_tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_ps_tree.c.s
.PHONY : src/lib/utils/cmon_ps_tree.c.s

src/lib/utils/cmon_string.o: src/lib/utils/cmon_string.c.o
.PHONY : src/lib/utils/cmon_string.o

# target to build an object file
src/lib/utils/cmon_string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_string.c.o
.PHONY : src/lib/utils/cmon_string.c.o

src/lib/utils/cmon_string.i: src/lib/utils/cmon_string.c.i
.PHONY : src/lib/utils/cmon_string.i

# target to preprocess a source file
src/lib/utils/cmon_string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_string.c.i
.PHONY : src/lib/utils/cmon_string.c.i

src/lib/utils/cmon_string.s: src/lib/utils/cmon_string.c.s
.PHONY : src/lib/utils/cmon_string.s

# target to generate assembly for a file
src/lib/utils/cmon_string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_string.c.s
.PHONY : src/lib/utils/cmon_string.c.s

src/lib/utils/cmon_string_array.o: src/lib/utils/cmon_string_array.c.o
.PHONY : src/lib/utils/cmon_string_array.o

# target to build an object file
src/lib/utils/cmon_string_array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_string_array.c.o
.PHONY : src/lib/utils/cmon_string_array.c.o

src/lib/utils/cmon_string_array.i: src/lib/utils/cmon_string_array.c.i
.PHONY : src/lib/utils/cmon_string_array.i

# target to preprocess a source file
src/lib/utils/cmon_string_array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_string_array.c.i
.PHONY : src/lib/utils/cmon_string_array.c.i

src/lib/utils/cmon_string_array.s: src/lib/utils/cmon_string_array.c.s
.PHONY : src/lib/utils/cmon_string_array.s

# target to generate assembly for a file
src/lib/utils/cmon_string_array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/lib/utils/cmon_string_array.c.s
.PHONY : src/lib/utils/cmon_string_array.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cmon.dir/build.make CMakeFiles/cmon.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cmon"
	@echo "... src/lib/cmon_config.o"
	@echo "... src/lib/cmon_config.i"
	@echo "... src/lib/cmon_config.s"
	@echo "... src/lib/cmon_errors.o"
	@echo "... src/lib/cmon_errors.i"
	@echo "... src/lib/cmon_errors.s"
	@echo "... src/lib/cmon_inotify.o"
	@echo "... src/lib/cmon_inotify.i"
	@echo "... src/lib/cmon_inotify.s"
	@echo "... src/lib/cmon_print.o"
	@echo "... src/lib/cmon_print.i"
	@echo "... src/lib/cmon_print.s"
	@echo "... src/lib/parser/cmon_parser.o"
	@echo "... src/lib/parser/cmon_parser.i"
	@echo "... src/lib/parser/cmon_parser.s"
	@echo "... src/lib/utils/cmon_int_array.o"
	@echo "... src/lib/utils/cmon_int_array.i"
	@echo "... src/lib/utils/cmon_int_array.s"
	@echo "... src/lib/utils/cmon_ps_tree.o"
	@echo "... src/lib/utils/cmon_ps_tree.i"
	@echo "... src/lib/utils/cmon_ps_tree.s"
	@echo "... src/lib/utils/cmon_string.o"
	@echo "... src/lib/utils/cmon_string.i"
	@echo "... src/lib/utils/cmon_string.s"
	@echo "... src/lib/utils/cmon_string_array.o"
	@echo "... src/lib/utils/cmon_string_array.i"
	@echo "... src/lib/utils/cmon_string_array.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

